vich_uploader:
    db_driver: orm

    mappings:
       post:
           uri_prefix: /upload/post
           upload_destination: '%kernel.project_dir%/public/upload/post'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

